apiVersion: apps/v1

kind: Deployment

metadata:

  creationTimestamp: null

  labels:

    app: messages

  name: messages

spec:

  replicas: 1

  selector:

    matchLabels:

      app: messages

  strategy: {}

  template:

    metadata:

      creationTimestamp: null

      labels:

        app: messages

    spec:

      containers:

      - image: org.ac.cst8277.hesse.ryan:local

        name: messages-service

        resources: {}

status: {}

---

apiVersion: v1

kind: Service

metadata:

  creationTimestamp: null

  labels:

    app: messages

  name: messages

spec:

  ports:

  - name: 8080-8080

    port: 8080

    protocol: TCP

    targetPort: 8080

  selector:

    app: messages

  type: NodePort

status:

  loadBalancer: {}